name: Stage deployment

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs: 
      commit_ids: ${{ steps.list-commits.outputs.commits }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: List commits in PR
        id: list-commits
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pr_number=${{ github.event.pull_request.number }}
          repo=${{ github.repository }}
          api_url="https://api.github.com/repos/$repo/pulls/$pr_number/commits"
          commits=$(curl -s -H "Authorization: token $GH_TOKEN" $api_url | jq -r '.[].sha')
          commits=$(echo $commits | tr '\n' ',')
          commits_list=${commits%,}
          echo "Commit hashes from stage branch:"
          echo "$commits_list"
          echo "commits=$commits_list" >> "$GITHUB_OUTPUT"

  cd:
    needs: ci
    environment: 
       name: STG
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
        # Loop through each hash and display it
        for hash in ${{ needs.ci.outputs.commit_ids }}; do
          echo "testing $hash"
        done
            
