name: Stage deployment

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs: 
      commit_ids: ${{ steps.list-commits.outputs.commits }}
      pr_number:  ${{ steps.list-commits.outputs.pr_number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: List commits in PR
        id: list-commits
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pr_number=${{ github.event.pull_request.number }}
          repo=${{ github.repository }}
          api_url="https://api.github.com/repos/$repo/pulls/$pr_number/commits"
          commits=$(curl -s -H "Authorization: token $GH_TOKEN" $api_url | jq -r '.[].sha')
          commits=$(echo $commits | tr '\n' ',')
          commits_list=${commits%,}
          echo "Commit hashes from stage branch:"
          echo "$commits_list"
          echo "commits=$commits_list" >> "$GITHUB_OUTPUT"
          echo "pr_number=$pr_number" >> "$GITHUB_OUTPUT"

  wait-for-approval:
    name: Wait For Approval
    needs: [ci]
    runs-on: ubuntu-latest
    environment: 
       name: STG
    steps:
      - name: check PR is merged!
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ls
          pr_number=${{ github.event.pull_request.number }}
          repo=${{ github.repository }}
          api_url="https://api.github.com/repos/$repo/pulls/${{ needs.ci.outputs.pr_number }}"
          # Get PR details
          response=$(curl -s -H "Authorization: token $GH_TOKEN" $api_url)
          # Check if the PR is merged
          merged=$(echo "$response" | jq -r '.merged')
          
          if [ "$merged" == "true" ]; then
            echo "The PR is merged"
            echo "Approved to deploy changes to stage branch"
          else
            echo "The PR is not merged"
            echo "Approved Failed"
            exist 1
          fi
  cd:
    needs: [ci, wait-for-approval]
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
        # Loop through each hash and display it
        for hash in ${{ needs.ci.outputs.commit_ids }}; do
          echo "testing $hash"
        done
            
