name: List Commits from Merged Branch

on:
  push:
    branches:
      - main

jobs:
  list-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List commits from merged branch
      run: |
        # Fetch all branches and tags
        git fetch --all

        # Get the name of the merged branch (assuming the branch name is passed as an input)
        MERGED_BRANCH_NAME="stage"

        # List all commits from the merged branch
        git log main..$MERGED_BRANCH_NAME --oneline
