name: Stage deployment

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs: 
      commit_ids: ${{ steps.list-commits.outputs.commits }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: List commits in PR
        id: list-commits
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pr_number=${{ github.event.pull_request.number }}
          commits=$(gh pr view $pr_number --json commits --jq '.commits[].oid')
          commits=$(echo $commits | tr '\n' ',')
          commits_list=${commits%,}
          echo "Commit hashes from stage branch:"
          echo "$commits_list"
          echo "commits=$commits_list" >> "$GITHUB_OUTPUT"

  cd:
    needs: ci
    environment: 
       name: STG
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
        Convert the space-separated string into an array
        echo "${{ needs.ci.outputs.commit_ids }}"
        # IFS=' ' read -r -a hash_array <<< 
        # IFS=' ' read -r -a hash_array <<< ${{ needs.ci.outputs.commit_ids }}
        # # Loop through each hash and display it
        # for hash in "${hash_array[@]}"; do
        #   echo "testing $hash"
        # done
            
